import { Capacitor } from '@capacitor/core';
import {
  Directory,
  Filesystem,
} from '@capacitor/filesystem';
import { FileViewer } from '@capacitor/file-viewer';

export type PaymentReceiptData = {
  paymentId: string;
  orderNumber: string;
  amountLabel: string;
  paymentType: string;
  paymentMethod: string;
  submittedAt: string;
  verifiedAt: string;
  status: string;
};

export type PaymentReceiptResult = {
  mode: 'opened' | 'saved' | 'downloaded';
  fileName: string;
};

const RECEIPT_DIRECTORY = 'Shop2Bhutan/Receipts';

function asciiText(value: unknown) {
  return String(value ?? '')
    .normalize('NFKD')
    .replace(/[^\x20-\x7E]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function safeFilePart(value: unknown, fallback: string) {
  const clean = asciiText(value)
    .replace(/[^a-zA-Z0-9_-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48);

  return clean || fallback;
}

function escapePdfText(value: string) {
  return asciiText(value)
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');
}

function wrapText(value: string, maxLength = 76) {
  const words = asciiText(value).split(' ').filter(Boolean);
  const lines: string[] = [];
  let current = '';

  for (const word of words) {
    const next = current ? `${current} ${word}` : word;

    if (next.length <= maxLength) {
      current = next;
      continue;
    }

    if (current) lines.push(current);
    current = word;
  }

  if (current) lines.push(current);

  return lines.length ? lines : ['-'];
}

function textOperator(
  text: string,
  x: number,
  y: number,
  size: number,
  font = 'F1',
) {
  return `BT /${font} ${size} Tf 1 0 0 1 ${x} ${y} Tm (${escapePdfText(
    text,
  )}) Tj ET`;
}

function buildReceiptPdf(data: PaymentReceiptData) {
  const receiptNumber = `S2B-PAY-${safeFilePart(
    data.paymentId,
    'RECEIPT',
  )
    .slice(0, 12)
    .toUpperCase()}`;

  const contentLines: string[] = [
    '0.96 0.96 0.96 rg 36 690 523 92 re f',
    '0.95 0.37 0.08 rg 36 690 8 92 re f',
    '0 0 0 rg',
    textOperator('Shop2Bhutan', 58, 746, 22, 'F2'),
    textOperator('Verified Payment Receipt', 58, 719, 13, 'F1'),
    textOperator(receiptNumber, 400, 744, 10, 'F1'),
    textOperator('PAYMENT DETAILS', 42, 655, 10, 'F2'),
    '0.86 0.86 0.86 RG 42 646 511 0.5 re S',
  ];

  const rows: Array<[string, string]> = [
    ['Order number', `#${asciiText(data.orderNumber) || '-'}`],
    ['Amount received', asciiText(data.amountLabel) || '-'],
    ['Payment type', asciiText(data.paymentType) || '-'],
    ['Payment method', asciiText(data.paymentMethod) || '-'],
    ['Submitted', asciiText(data.submittedAt) || '-'],
    ['Verified', asciiText(data.verifiedAt) || '-'],
    ['Status', asciiText(data.status) || 'Verified'],
  ];

  let y = 620;

  for (const [label, value] of rows) {
    contentLines.push(
      textOperator(label, 48, y, 10, 'F1'),
      textOperator(value, 220, y, 11, 'F2'),
    );
    y -= 34;
  }

  contentLines.push(
    '0.86 0.86 0.86 RG 42 368 511 0.5 re S',
    textOperator('Receipt note', 42, 342, 10, 'F2'),
  );

  const noteLines = wrapText(
    'This receipt confirms that Shop2Bhutan marked the listed payment as verified. Keep this document for your records and quote the order number when contacting support.',
  );

  let noteY = 318;

  for (const line of noteLines) {
    contentLines.push(textOperator(line, 42, noteY, 10, 'F1'));
    noteY -= 17;
  }

  contentLines.push(
    textOperator(
      'Generated by the Shop2Bhutan customer app.',
      42,
      96,
      9,
      'F1',
    ),
    textOperator(
      'This is a system-generated receipt and does not require a signature.',
      42,
      80,
      9,
      'F1',
    ),
    '0.95 0.37 0.08 rg 0 0 595 10 re f',
  );

  const content = contentLines.join('\n');
  const encoder = new TextEncoder();

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>',
    `<< /Length ${encoder.encode(content).length} >>\nstream\n${content}\nendstream`,
  ];

  let pdf = '%PDF-1.4\n';
  const offsets = [0];

  objects.forEach((object, index) => {
    offsets[index + 1] = encoder.encode(pdf).length;
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const xrefOffset = encoder.encode(pdf).length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';

  for (let index = 1; index <= objects.length; index += 1) {
    pdf += `${String(offsets[index]).padStart(10, '0')} 00000 n \n`;
  }

  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\n`;
  pdf += `startxref\n${xrefOffset}\n%%EOF\n`;

  return encoder.encode(pdf);
}

function bytesToBase64(bytes: Uint8Array) {
  let binary = '';
  const chunkSize = 0x8000;

  for (let offset = 0; offset < bytes.length; offset += chunkSize) {
    const chunk = bytes.subarray(
      offset,
      Math.min(offset + chunkSize, bytes.length),
    );

    binary += String.fromCharCode(...chunk);
  }

  return window.btoa(binary);
}

function downloadPdfInBrowser(
  bytes: Uint8Array,
  fileName: string,
) {
  const pdfBuffer = new ArrayBuffer(bytes.byteLength);
  new Uint8Array(pdfBuffer).set(bytes);

  const blob = new Blob([pdfBuffer], {
    type: 'application/pdf',
  });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');

  anchor.href = url;
  anchor.download = fileName;
  anchor.rel = 'noopener';
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();

  window.setTimeout(() => {
    URL.revokeObjectURL(url);
  }, 1500);
}

async function writeNativeReceipt(
  bytes: Uint8Array,
  fileName: string,
) {
  const relativePath = `${RECEIPT_DIRECTORY}/${fileName}`;
  const encodedPdf = bytesToBase64(bytes);

  try {
    return await Filesystem.writeFile({
      path: relativePath,
      data: encodedPdf,
      directory: Directory.Documents,
      recursive: true,
    });
  } catch (documentsError) {
    console.warn(
      '[PaymentReceipt] Documents storage unavailable, using app data:',
      documentsError,
    );

    return Filesystem.writeFile({
      path: relativePath,
      data: encodedPdf,
      directory: Directory.Data,
      recursive: true,
    });
  }
}

export async function openOrDownloadPaymentReceipt(
  data: PaymentReceiptData,
): Promise<PaymentReceiptResult> {
  if (data.status.toLowerCase() !== 'verified') {
    throw new Error(
      'A receipt is available only after payment verification.',
    );
  }

  const orderPart = safeFilePart(
    data.orderNumber,
    'Payment',
  );
  const fileName = `Shop2Bhutan-Payment-${orderPart}.pdf`;
  const pdfBytes = buildReceiptPdf(data);

  if (!Capacitor.isNativePlatform()) {
    downloadPdfInBrowser(pdfBytes, fileName);

    return {
      mode: 'downloaded',
      fileName,
    };
  }

  const writeResult = await writeNativeReceipt(
    pdfBytes,
    fileName,
  );

  try {
    await FileViewer.openDocumentFromLocalPath({
      path: writeResult.uri,
    });

    return {
      mode: 'opened',
      fileName,
    };
  } catch (viewerError) {
    console.warn(
      '[PaymentReceipt] Receipt saved but could not be opened:',
      viewerError,
    );

    return {
      mode: 'saved',
      fileName,
    };
  }
}
